import Head from 'next/head';
import { NextPage } from 'next';

import HomePage from '@screens/HomePage';
import Footer from '@containers/Footer';
import endpoints from '@constants/url';
import { CryptoCurrencyInterface } from '@interface/interface';
import { REVALIDATE_INTERVAL, ERROR_REVALIDATE_INTERVAL } from '@constants/constants';

const Home: NextPage<{ currencies: CryptoCurrencyInterface[] }> = ({ currencies }) => {
  return (
    <>
      <Head>
        <title>Harga Crypto Hari Ini (IDR) | Pintu | Denny Angesti Pratama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage currencies={currencies} />
      <Footer />
    </>
  );
};

export const getStaticProps = async () => {
  try {
    const res = await fetch(endpoints.supportedCurrencies);
    const data = await res.json();
    const payload: CryptoCurrencyInterface[] = data.payload;

    return {
      props: { currencies: payload },
      revalidate: REVALIDATE_INTERVAL,
    };
  } catch (error) {
    return {
      props: {
        currencies: [],
      },
      revalidate: ERROR_REVALIDATE_INTERVAL,
    };
  }
};

export default Home;
